# Orderer config
orderer:
  host: localhost:7050
  useTLS: false
  timeout: 5s
# Config of local peer
local_peer:
  host: localhost:7051
  tls:
    enabled: false
  timeout: 1s
  # GRPC parameters
  grpc:
    # Keep-Alive parameters
#    keep_alive:
#      time:


discovery:
  type: local
  options:
    channels:
      - name: public
        description: public channel for all members
        chaincodes:
        - name: network
          type: golang
          version: "0.1"
          description: system discovery chaincode
        peers:
          - host: localhost:7051
          - host: localhost:17051

crypto:
  type: ecdsa
  options:
    # Possible curves: P256, P384, P512
    curve: P256
    # Possible algorithms for signature: SHA256, SHA384, SHA512
    signatureAlgorithm: SHA256
    # Possible hashing algorithms: SHA2-256, SHA2-384, SHA3-256, SHA3-384
    hash: SHA2-256